from flask import Flask, render_template, jsonify
import json
from models import *

app = Flask(__name__, template_folder='templates')
app.config.from_object(__name__)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()
    if Board.table_exists() and Card.table_exists() and Meta.table_exists():
        pass
    else:
        db.create_table(Board, safe=True)
        db.create_table(Card, safe=True)
        db.create_table(Meta, safe=True)


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()


@app.route('/')
def index():
    return render_template("index.html")


@app.route('/api/boards')
def board_level():
    list_of_boards = []
    for board in Board.select():
        list_of_boards.append({"id": board.id,
                               "title": board.title,
                               "color": board.color,
                               "listOfCards": []})
    return json.dumps({"list_of_boards": list_of_boards})


@app.route('/api/<board_id>/cards/')
def card_level(board_id):
    list_of_cards = []
    for card in Card.select():
        if card.board.id == int(board_id):
            list_of_cards.append({"id": card.id,
                                  "title": card.title,
                                  "color": card.color})
    return json.dumps(list_of_cards)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)