from flask import Flask, render_template, jsonify
import json
from models import *

app = Flask(__name__)
app.config.from_object(__name__)


def db_to_json():
    list_of_boards = []
    for board in Board.select():
        list_of_boards.append({"id": board.id,
                               "title": board.title,
                               "color": board.color,
                               "listOfCards": []})
    for board in list_of_boards:
        for card in Card.select().where(Card.board == board["id"]):
            board["listOfCards"].append({"id": card.id,
                                         "title": card.title,
                                         "color": card.color,
                                         "board": card.board.id})
    return list_of_boards


def save_to_db(my_json, entity="board"):
    if (entity == "board"):
        curr_board = my_json["board"]
        Board.create(title=curr_board["title"], color=curr_board["color"])
    elif (entity == "card"):
        curr_card = my_json["card"]
        Card.create(title=curr_card["title"], color=curr_card["color"], board=curr_card["board"])


def update_db(my_json, entity="board"):
    if (entity == "board"):
        curr_board = my_json["board"]
        db_board = Board.get(Board.id == curr_board["id"])
        db_board.title = curr_board["title"]
        db_board.save()
        #Board.update(Board.title=curr_board["title"]).where(Board.id == curr_board["id"])
    elif (entity == "card"):
        curr_card = my_json["card"]
        db_card = Card.get(Card.id == curr_card["id"])
        db_card.title = curr_card["title"]
        db_card.save()
        #Card.update(Card.title=curr_card["title"]).where(Card.id == curr_card["id"])


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()
    if Board.table_exists() and Card.table_exists() and Meta.table_exists():
        pass
    else:
        db.create_table(Board, safe=True)
        db.create_table(Card, safe=True)
        db.create_table(Meta, safe=True)
        Meta.create(page_state='board_level')


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()


@app.route('/')
def index():
    return render_template("index.html")


@app.route('/api/boards')
def board_level():
    list_of_boards = db_to_json()
    return json.dumps({"list_of_boards": list_of_boards})


@app.route('/api/<board_id>/cards/')
def card_level(board_id):
    list_of_cards = []
    for card in Card.select():
        if card.board.id == int(board_id):
            list_of_cards.append({"id": card.id,
                                  "title": card.title,
                                  "color": card.color})
    return json.dumps({'list_of_cards': list_of_cards})


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
