from flask import Flask, render_template
from models import *

app = Flask(__name__, template_folder='templates')
app.config.from_object(__name__)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()
    if Board.table_exists() and Card.table_exists() and Meta.table_exists():
        pass
    else:
        db.create_table(Board, safe=True)
        db.create_table(Card, safe=True)
        db.create_table(Meta, safe=True)


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()


@app.route('/')
def index():
    return render_template("index.html")


@app.route('/api/boards')
def board_level():
    # need a class, which handles jsonifying Board objects
    data = 'JSON like: \'listOfBoards\': [Board objects]'
    return data


@app.route('/api/<board_id>/cards')
def card_level(board_id):
    # according to board_id it sends back the listOfCards attribute
    Card.select().where(Card.board.id == board_id)
    data = 'JSON like: \'listOfCards\': [Card objects]'
    return data

if __name__ == '__main__':
    app.run(debug=True)
